C***********************************************************************
C INCLUDE FILE maslovpar.inc
C
C PURPOSE: Define parameters controlling the maslov integral
C          
C          
C
C***********************************************************************

C---  Maslov flip index:
      INTEGER     KFLP_0,KFLP_X,KFLP_Y,KFLP_2
      PARAMETER ( KFLP_0 = 0 )
      PARAMETER ( KFLP_X = 1 )
      PARAMETER ( KFLP_Y = 2 )
      PARAMETER ( KFLP_2 = 3 )
