C***********************************************************************
C INCLUDE FILE math_const.inc
C
C PURPOSE: Define mathematical constants
C          
C
C PROGRAMMED : KETIL HOKSTAD JANUARY 1999
C
C***********************************************************************

      REAL       PI
      PARAMETER (PI=3.14159265)

      COMPLEX    CI  
      PARAMETER (CI=(0.0,1.0))       ! Imaginary unit 

C***********************************************************************
C   END OF INCLUDE FILE math_const.inc
C***********************************************************************


