************************************************************
* JOBFILE FOR IKU ANISOTROPIC RAY TRACER Version 1.0       *
************************************************************
****************************************
* GENERAL PARAMETERS                   *
****************************************
RAY TRACING MODE      (SOURCE/RECEIVER): SOURCE
ONE-WAY WAVE MODES          (P0 S1 S2) : P0 S1 S2
CORNER GLOBAL GRID        (x,y,z) in m :      0.0      0.0      0.0
SAMPLING GLOBAL GRID   (dx,dy,dz) in m :     12.5     12.5     12.5
SIZE GLOBAL GRID            (nx,ny,nz) :      401        1      241
LOG FILE              (file name/none) : art_log.txt    
****************************************
* SURVEY                               *
* m1: regular bins (Thomsen param)     *
* m2: irregular bins                   * 
****************************************
INPUT MODE                             : m1
DESCRIPTION FILE FOR SOR/REC BINS      : kam_sor_m1.txt
MEDIUM AT SOR/REC BINS (anis/elas/acou): acou
DATA BASE FOR SOR/REC BINS             : kam_sor_bins_data_base.txt
****************************************
* ILLUMINATION GRIDS                   *
****************************************   
DESCRIPTION FILE                       : kam_illum.txt
DATA BASE FOR P0 SOR/REC GRIDS         : kam_sor_P0_illum_data_base.txt
DATA BASE FOR S1 SOR/REC GRIDS         : kam_sor_S1_illum_data_base.txt
DATA BASE FOR S2 SOR/REC GRIDS         : kam_sor_S2_illum_data_base.txt
****************************************
* GEOLOGICAL MODEL                     * 
* m1: Thomsen parameters               *
* m2: Voigt parameters                 *
* m3: Tsvankin parameters (A2, A4, A5) *
****************************************
INPUT MODE                             : m1
DESCRIPTION FILE                       : kam_model_m1.txt
FORMAT MODEL FILES            (dir/seq): dir
Anis. symmetry    (TIV/TIH/TIG/ORV/ORG): TIV          
Order of interpol. polynomial   (NPOLY):   5
****************************************
* RAYS                                 * 
* m1: traveltime only (and maxpat=1)   *
* m2: time, gdiv, p_surf               *
* m3: kmah, time, gdiv, p_surf, g_surf *
* m4: same as m3 + p_down              *
****************************************
RAY MODE                               : m4
FORMAT RAY FILES             (dir/seq) : dir
DIMENSION GEOM SPREADING       (1/2/3) : 2
ROOT NAME P0 SOR/REC RAY DATA BASE     : kam_sor_P0_ray_data_base.dir
ROOT NAME S1 SOR/REC RAY DATA BASE     : kam_sor_S1_ray_data_base.dir
ROOT NAME S2 SOR/REC RAY DATA BASE     : kam_sor_S2_ray_data_base.dir
****************************************
* SHOOTING DIRECTIONS                  *
****************************************
No of polar angles               (NPOL): 161
No of azimuth angles             (NAZ2):   0
Min polar angle (-90,90)        (APOL1): -20.0
Max polar angle (-90,90)        (APOL2):  20.0
Min azimuth angle (0,360)       (AAZI1):   0.0
Max azimut angle (0,360)        (AAZI2):   0.0
****************************************
* ADAPTIVE 4TH ORDER RUNGE KUTTA       *
****************************************
Max no of ray elements          (MAXEL): 802
Initial time      (s)              (TO):   0.0
Max traveltime    (s)              (T1):   2.2
Initial time step (s)              (H0):   0.011
Min time step     (s)            (HMIN):   0.001
Required accuracy               (ACCUR):   0.001
****************************************
* RAY TRACING OPTIONS                  *
****************************************
Kinetic ray tracing (ON/OFF)           : ON
Dynamic ray tracing (ON/OFF)           : ON
Initial ray direction (UP/DOWN)        : DOWN
Sol. of Christoffel eq. (FAST/JACOBI)  : JACOBI
****************************************
* LOGFILE AND SCRATCH DIRECTORIES      *
****************************************
Error messages and warnings     (ascii): vh_errmsg.txt
Scratch/Work directory 1      (WRKDIR1): /not_used
Scratch/Work directory 2      (WRKDIR2): /not_used
************************************************************
*                   END OF JOB FILE                        *
************************************************************



